### ISSUE TITLE
ValueError when a single parameter is supplied to GASearchCV

### ISSUE THREAD

**Issue by poroc300** [rodrigo-arenas/Sklearn-genetic-opt#65]
**System information**
OS Platform and Distribution: Windows 10
Sklearn-genetic-opt  version: 0.6.0
Scikit-learn version: 0.24.1
Python version: 3.8

**Describe the bug**
`GASearchCV` raises a `ValueError : empty range for randrange() (1, 1, 0)` after generation 0 when only one parameter is supplied to the argument `param_grid`. I am not 100% sure if this is a true bug or if this is an expected behaviour of the genetic algorithm; nonetheless, I have decided to raise this issue because the error is not very clear about what is happening (in my opinion).

**To Reproduce**
Below, I am showing two examples of this error when using a `SVR` and `RandomForestClassifier` with a single parameter for optimization. I have tested other algorithms and I have got the same error.

```
import numpy as np
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, KFold
from sklearn_genetic import GASearchCV
from sklearn_genetic.space import Continuous, Categorical, Integer
from sklearn.ensemble import RandomForestClassifier

#generate input to test SVR for regression and random forest for classification
X = np.random.normal(75, 10, (1000, 2))
y = np.random.normal(200, 20, 1000)
y_labels = np.random.randint(0, 2, size=1000)
cv = KFold(n_splits=5, random_state=42, shuffle=True)
```

This is the example for `SVR`:
```
params_svr = {"degree": Integer(2,3)}

evolved = GASearchCV(estimator=SVR(),
                     cv=cv,
                     population_size=10,
                     generations=40,
                     tournament_size=5,
                     elitism=True,
                     crossover_probability=0.85,
                     mutation_probability=0.1,
                     param_grid=params_svr,
                     criteria='max',
                     scoring="neg_mean_absolute_error",
                     algorithm='eaMuPlusLambda',
                     error_score="raise",
                     n_jobs=-1,
                     verbose=True,
                     keep_top_k=10)

evolved.fit(X, y)
```

This is the example for ```RandomForestClassifier```:
```
params_rfc = {"max_depth": Integer(2,6)}

evolved = GASearchCV(estimator=RandomForestClassifier(),
                     cv=cv,
                     population_size=10,
                     generations=40,
                     tournament_size=5,
                     elitism=True,
                     crossover_probability=0.85,
                     mutation_probability=0.1,
                     param_grid=params_rfc,
                     criteria='max',
                     scoring="f1",
                     algorithm='eaMuPlusLambda',
                     error_score="raise",
                     n_jobs=-1,
                     verbose=True,
                     keep_top_k=10)

evolved.fit(X, y_labels)
```

**Expected behavior**
If I add an extra parameter to `params_svr` and `params_rfc`:
```
params_svr = {"degree": Integer(2,3), "C": Continuous(0, 1)}
params_rfc = {"max_depth": Integer(2,6), "criterion": Categorical(["gini", "entropy"])}
```
The algorithm runs as usual.

**Screenshots**
Please find below the full log of this error.

```
Traceback (most recent call last):

  File "<ipython-input-15-82a4ae8a09ac>", line 17, in <module>
    evolved.fit(X, y_labels)

  File "C:\Users\andre\Anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 120, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)

  File "C:\Users\andre\Anaconda3\lib\site-packages\sklearn_genetic\genetic_search.py", line 455, in fit
    pop, log, n_gen = self._select_algorithm(

  File "C:\Users\andre\Anaconda3\lib\site-packages\sklearn_genetic\genetic_search.py", line 547, in _select_algorithm
    pop, log, gen = eaMuPlusLambda(

  File "C:\Users\andre\Anaconda3\lib\site-packages\sklearn_genetic\algorithms.py", line 305, in eaMuPlusLambda
    offspring = varOr(population, toolbox, lambda_, cxpb, mutpb)

  File "C:\Users\andre\Anaconda3\lib\site-packages\deap\algorithms.py", line 234, in varOr
    ind1, ind2 = toolbox.mate(ind1, ind2)

  File "C:\Users\andre\Anaconda3\lib\site-packages\deap\tools\crossover.py", line 51, in cxTwoPoint
    cxpoint2 = random.randint(1, size - 1)

  File "C:\Users\andre\Anaconda3\lib\random.py", line 248, in randint
    return self.randrange(a, b+1)

  File "C:\Users\andre\Anaconda3\lib\random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))

ValueError: empty range for randrange() (1, 1, 0)
```

**Comment by rodrigo-arenas** [comment]
Hi, thanks.
This is somehow the expected behavior, the way the new candidates are created in generation 1, is by using a [crossover](https://deap.readthedocs.io/en/master/api/tools.html#deap.tools) operation, which is a DEAP`tools.cxTwoPoint`, this function needs to sample 2 random points from each individuals parameter, as it has length 1, it can't be done.

To fix this, I'll introduce the `tools.cxSimulatedBinaryBounded` which can handle 1 parameter, but it won't probably be able to make a real optimization and get stuck in one single random value, so at the same time, a warning will be raised indicating that at least 2 parameters are advised to actually make an optimization, but an error won't be longer be raised.

**Comment by poroc300** [comment]
Thank you very much for the explanation.
